# Generated by Django 2.2.6 on 2019-10-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='Femenino', max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltere'), ('casado', 'Casade'), ('divorciado', 'Divorciade'), ('viudo', 'Viude')], default='Soltero', max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=8)),
                ('celular', models.CharField(max_length=10)),
                ('direccion', models.CharField(default='sin direccion', max_length=150)),
            ],
        ),
    ]
