# Generated by Django 2.2.6 on 2019-10-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros')], default='Ahorros', max_length=30)),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.client')),
            ],
        ),
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('transaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('deposito', 'Deposito'), ('retiro', 'Retiro'), ('transferencia', 'Transferencia')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=160)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.cuenta')),
            ],
        ),
    ]
