# Generated by Django 2.2.6 on 2019-10-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_cuenta_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='estado_civil',
            field=models.CharField(choices=[('soltero', 'Soltere'), ('casado', 'Casade'), ('divorciado', 'Divorciade'), ('viudo', 'Viude')], default='soltero', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=15),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros')], default='ahorros', max_length=30),
        ),
    ]
