# Generated by Django 2.2.6 on 2019-10-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20191024_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='direccion',
            field=models.TextField(default='sin direccion', max_length=150),
        ),
    ]
